# Generated by Django 5.0.6 on 2024-08-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]
