# Generated by Django 5.0.6 on 2024-10-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0006_alter_candidate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='won_categories', to='candidates.candidate')),
            ],
        ),
    ]
