# Generated by Django 5.0.6 on 2024-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='points',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4')]),
        ),
    ]
