# Generated by Django 5.0.6 on 2024-11-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_category_image_alter_vote_points'),
        ('voting', '0008_alter_vote_points'),
    ]

    operations = [
    ]
