# Generated by Django 5.0.6 on 2024-07-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_nationality_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='nationality',
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.ManyToManyField(to='candidates.nationality'),
        ),
    ]
