# Generated by Django 5.0.6 on 2024-07-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_nationality_candidate_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidate_images/')),
                ('main_image', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='candidates.candidate')),
            ],
        ),
    ]
